name: Py3 Test

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install format and testing packages.
        run: pip install . black==20.8b1 pytest

      - name: Run Linter
        run: black --diff --check phabricator_task_links
